In [2]:
import pandas as pd
from sklearn import linear_model, model_selection
import numpy as np
# test
products = '/Users/paddy/Desktop/facebook_products.csv'

df =  pd.read_csv(products)
df.head()

,Unnamed: 0,id,product_name,category,product_description,price,location,url,page_id,create_time
0,0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",£5.00,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26
1,1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richard’s (model no 48755)Stainless ste...,£20.00,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26
2,2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I don’t...,£20.00,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26
3,3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,£115.00,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26
4,4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,"Home & Garden / Dining, Living Room Furniture ...",New Design Shannon Corner sofa 5 Seater Avail...,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info

<bound method DataFrame.info of       Unnamed: 0                                    id  \
0              0  243809c0-9cfc-4486-ad12-3b7a16605ba9
1              1  1c58d3f9-8b93-47ea-9415-204fcc2a22e6
2              2  860673f1-57f6-47ba-8d2f-13f9e05b8f9a
3              3  59948726-29be-4b35-ade5-bb2fd7331856
4              4  16dbc860-696e-4cda-93f6-4dd4926573fb
...          ...                                   ...
11313       7151  c4148656-78a9-4f3e-b393-134fdc5ef900
11314       7152  564e3411-768d-4250-a624-b119d696f103
11315       7153  2b0a652b-46a2-4297-b619-5efeeb222787
11316       7154  719fd40a-870e-4144-b324-55dff2e66fb4
11317       7155  86d1806b-5575-4a7e-9160-f24f12be6c95

                                            product_name  \
0      Mirror wall art | in Wokingham, Berkshire | Gu...
1      Stainless Steel Food Steamer | in Inverness, H...
2      Sun loungers | in Skegness, Lincolnshire | Gum...
3      Coffee side table from Ammunition ammo box hai...
4      Modern Shannon Sofa for sale at low cost | in ...
...                                                  ...
11313  Sony PlayStation VR Move Bundle | in Acocks Gr...
11314  Playstation VR V2 Bundle | in Acocks Green, We...
11315  Oculus quest 2 256gb | in Montrose, Angus | Gu...
11316  Logitech driving force shifter | in Carrickfer...
11317  20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...

                                                category  \
0      Home & Garden / Dining, Living Room Furniture ...
1                  Home & Garden / Other Household Goods
2      Home & Garden / Garden & Patio / Outdoor Setti...
3      Home & Garden / Dining, Living Room Furniture ...
4      Home & Garden / Dining, Living Room Furniture ...
...                                                  ...
11313  Video Games & Consoles / Consoles / PS4 (Sony ...
11314  Video Games & Consoles / Consoles / PS4 (Sony ...
11315  Video Games & Consoles / Other Video Games & C...
11316  Video Games & Consoles / Video Game Accessorie...
11317                     Video Games & Consoles / Games

                                     product_description    price  \
0      Mirror wall art. Posted by Nisha in Dining, Li...    £5.00
1      Morphy Richard’s (model no 48755)Stainless ste...   £20.00
2      I have 2 of these - collection only as I don’t...   £20.00
3      Great reclaimed army ammunition box used as co...  £115.00
4      New Design Shannon Corner sofa  5 Seater Avail...      NaN
...                                                  ...      ...
11313  Sony PlayStation VR Move Bundle353CASH ON COLL...  £260.00
11314  Playstation VR V2 Bundle355CASH ON COLLECTION ...  £235.00
11315  Pick up only £250Comes with two pistols stocks...  £250.00
11316  Bought at christmas from currys retailing at £...   £30.00
11317  Nintendo Switch console only used 2/3 times. A...  £450.00

                           location  \
0              Wokingham, Berkshire
1               Inverness, Highland
2            Skegness, Lincolnshire
3                Radstock, Somerset
4                               NaN
...                             ...
11313   Acocks Green, West Midlands
11314   Acocks Green, West Midlands
11315               Montrose, Angus
11316  Carrickfergus, County Antrim
11317                 Poole, Dorset

                                                     url       page_id  \
0      https://www.gumtree.com/p/mirrors-clocks-ornam...  1.426705e+09
1      https://www.gumtree.com/p/other-household-good...  1.426705e+09
2      https://www.gumtree.com/p/outdoor-settings-fur...  1.426705e+09
3      https://www.gumtree.com/p/other-dining-living-...  1.426705e+09
4                                                    NaN           NaN
...                                                  ...           ...
11313  https://www.gumtree.com/p/ps4/sony-playstation...  1.422159e+09
11314  https://www.gumtree.com/p/ps4/playstation-vr-v...  1.422159e+09
11315  https://www.gumtree.com/p/other-video-games/oc...  1.426669e+09
11316  https://www.gumtree.com/p/other-video-game-acc...  1.426700e+09
11317  https://www.gumtree.com/p/video-games/20-games...  1.426700e+09

      create_time
0      2022-02-26
1      2022-02-26
2      2022-02-26
3      2022-02-26
4             NaN
...           ...
11313  2022-02-28
11314  2022-02-28
11315  2022-02-28
11316  2022-02-28
11317  2022-02-28

[11318 rows x 10 columns]>

In [4]:
df.dtypes

Unnamed: 0              object
id                      object
product_name            object
category                object
product_description     object
price                   object
location                object
url                     object
page_id                float64
create_time             object
dtype: object

In [5]:
df[['id','product_name','category','product_description','location','url','create_time']] = df[['id','product_name','category','product_description','location','url','create_time']].astype(str)
df.dtypes

Unnamed: 0              object
id                      object
product_name            object
category                object
product_description     object
price                   object
location                object
url                     object
page_id                float64
create_time             object
dtype: object

In [6]:
df = df.drop(df.columns[0], axis=1)
df['product_name'] = df['product_name'].str.encode('ascii', 'ignore').str.decode('ascii')
df['product_description'] = df['product_description'].str.encode('ascii', 'ignore').str.decode('ascii')
df.head()

,id,product_name,category,product_description,price,location,url,page_id,create_time
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",£5.00,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richards (model no 48755)Stainless stee...,£20.00,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I dont ...,£20.00,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,£115.00,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26
4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,"Home & Garden / Dining, Living Room Furniture ...",New Design Shannon Corner sofa 5 Seater Avail...,NaN,nan,nan,NaN,nan

In [7]:
df = df.dropna(axis=0)
df.info

<bound method DataFrame.info of                                          id  \
0      243809c0-9cfc-4486-ad12-3b7a16605ba9
1      1c58d3f9-8b93-47ea-9415-204fcc2a22e6
2      860673f1-57f6-47ba-8d2f-13f9e05b8f9a
3      59948726-29be-4b35-ade5-bb2fd7331856
12     5707be4f-49d9-4feb-b2c8-aa0868405c65
...                                     ...
11313  c4148656-78a9-4f3e-b393-134fdc5ef900
11314  564e3411-768d-4250-a624-b119d696f103
11315  2b0a652b-46a2-4297-b619-5efeeb222787
11316  719fd40a-870e-4144-b324-55dff2e66fb4
11317  86d1806b-5575-4a7e-9160-f24f12be6c95

                                            product_name  \
0      Mirror wall art | in Wokingham, Berkshire | Gu...
1      Stainless Steel Food Steamer | in Inverness, H...
2      Sun loungers | in Skegness, Lincolnshire | Gum...
3      Coffee side table from Ammunition ammo box hai...
12     Spotlights | in Newent, Gloucestershire | Gumtree
...                                                  ...
11313  Sony PlayStation VR Move Bundle | in Acocks Gr...
11314  Playstation VR V2 Bundle | in Acocks Green, We...
11315  Oculus quest 2 256gb | in Montrose, Angus | Gu...
11316  Logitech driving force shifter | in Carrickfer...
11317  20 GAMES & NINTENDO SWITCH BUNDLE | in Poole, ...

                                                category  \
0      Home & Garden / Dining, Living Room Furniture ...
1                  Home & Garden / Other Household Goods
2      Home & Garden / Garden & Patio / Outdoor Setti...
3      Home & Garden / Dining, Living Room Furniture ...
12                 Home & Garden / Other Household Goods
...                                                  ...
11313  Video Games & Consoles / Consoles / PS4 (Sony ...
11314  Video Games & Consoles / Consoles / PS4 (Sony ...
11315  Video Games & Consoles / Other Video Games & C...
11316  Video Games & Consoles / Video Game Accessorie...
11317                     Video Games & Consoles / Games

                                     product_description    price  \
0      Mirror wall art. Posted by Nisha in Dining, Li...    £5.00
1      Morphy Richards (model no 48755)Stainless stee...   £20.00
2      I have 2 of these - collection only as I dont ...   £20.00
3      Great reclaimed army ammunition box used as co...  £115.00
12     New in box not needed Spotlights . Posted by s...    £9.00
...                                                  ...      ...
11313  Sony PlayStation VR Move Bundle353CASH ON COLL...  £260.00
11314  Playstation VR V2 Bundle355CASH ON COLLECTION ...  £235.00
11315  Pick up only 250Comes with two pistols stocks ...  £250.00
11316  Bought at christmas from currys retailing at 4...   £30.00
11317  Nintendo Switch console only used 2/3 times. A...  £450.00

                           location  \
0              Wokingham, Berkshire
1               Inverness, Highland
2            Skegness, Lincolnshire
3                Radstock, Somerset
12          Newent, Gloucestershire
...                             ...
11313   Acocks Green, West Midlands
11314   Acocks Green, West Midlands
11315               Montrose, Angus
11316  Carrickfergus, County Antrim
11317                 Poole, Dorset

                                                     url       page_id  \
0      https://www.gumtree.com/p/mirrors-clocks-ornam...  1.426705e+09
1      https://www.gumtree.com/p/other-household-good...  1.426705e+09
2      https://www.gumtree.com/p/outdoor-settings-fur...  1.426705e+09
3      https://www.gumtree.com/p/other-dining-living-...  1.426705e+09
12     https://www.gumtree.com/p/other-household-good...  1.426705e+09
...                                                  ...           ...
11313  https://www.gumtree.com/p/ps4/sony-playstation...  1.422159e+09
11314  https://www.gumtree.com/p/ps4/playstation-vr-v...  1.422159e+09
11315  https://www.gumtree.com/p/other-video-games/oc...  1.426669e+09
11316  https://www.gumtree.com/p/other-video-game-acc...  1.426700e+09
11317  https://www.gumtree.com/p/video-games/20-games...  1.426700e+09

      create_time
0      2022-02-26
1      2022-02-26
2      2022-02-26
3      2022-02-26
12     2022-02-26
...           ...
11313  2022-02-28
11314  2022-02-28
11315  2022-02-28
11316  2022-02-28
11317  2022-02-28

[6311 rows x 9 columns]>

In [8]:
df.head()

,id,product_name,category,product_description,price,location,url,page_id,create_time
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",£5.00,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richards (model no 48755)Stainless stee...,£20.00,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I dont ...,£20.00,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,£115.00,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,"Spotlights | in Newent, Gloucestershire | Gumtree",Home & Garden / Other Household Goods,New in box not needed Spotlights . Posted by s...,£9.00,"Newent, Gloucestershire",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26

In [9]:
df['price'] = df['price'].str.replace('£','')
df['price'] = df['price'].str.replace(',','').astype(float)
df.head()

,id,product_name,category,product_description,price,location,url,page_id,create_time
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richards (model no 48755)Stainless stee...,20.0,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I dont ...,20.0,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,"Spotlights | in Newent, Gloucestershire | Gumtree",Home & Garden / Other Household Goods,New in box not needed Spotlights . Posted by s...,9.0,"Newent, Gloucestershire",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26

In [10]:
df.dtypes

id                      object
product_name            object
category                object
product_description     object
price                  float64
location                object
url                     object
page_id                float64
create_time             object
dtype: object

In [11]:
# df['product_name'] = df['product_name'].astype('str')
# df['product_name'] = df['product_name'].str.replace('|','')

df['product_name'] = df['product_name'].str.split('|').str[0]
# df['product_name'] = df['product_name']
df.head()

,id,product_name,category,product_description,price,location,url,page_id,create_time
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,Mirror wall art,"Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,Stainless Steel Food Steamer,Home & Garden / Other Household Goods,Morphy Richards (model no 48755)Stainless stee...,20.0,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,Sun loungers,Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I dont ...,20.0,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,Spotlights,Home & Garden / Other Household Goods,New in box not needed Spotlights . Posted by s...,9.0,"Newent, Gloucestershire",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26

In [12]:
df['subcategory'] = df['category'].str.split('/').str[1]
df['category'] = df['category'].str.split('/').str[0]
df.head()

,id,product_name,category,product_description,price,location,url,page_id,create_time,subcategory
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,Mirror wall art,Home & Garden,"Mirror wall art. Posted by Nisha in Dining, Li...",5.0,"Wokingham, Berkshire",https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture"
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,Stainless Steel Food Steamer,Home & Garden,Morphy Richards (model no 48755)Stainless stee...,20.0,"Inverness, Highland",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,Sun loungers,Home & Garden,I have 2 of these - collection only as I dont ...,20.0,"Skegness, Lincolnshire",https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26,Garden & Patio
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Home & Garden,Great reclaimed army ammunition box used as co...,115.0,"Radstock, Somerset",https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture"
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,Spotlights,Home & Garden,New in box not needed Spotlights . Posted by s...,9.0,"Newent, Gloucestershire",https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods

In [13]:
df['county'] = df['location'].str.split(',').str[1]
df['location'] = df['location'].str.split(',').str[0]
df.head()
# fin

,id,product_name,category,product_description,price,location,url,page_id,create_time,subcategory,county
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,Mirror wall art,Home & Garden,"Mirror wall art. Posted by Nisha in Dining, Li...",5.0,Wokingham,https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture",Berkshire
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,Stainless Steel Food Steamer,Home & Garden,Morphy Richards (model no 48755)Stainless stee...,20.0,Inverness,https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods,Highland
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,Sun loungers,Home & Garden,I have 2 of these - collection only as I dont ...,20.0,Skegness,https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26,Garden & Patio,Lincolnshire
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Home & Garden,Great reclaimed army ammunition box used as co...,115.0,Radstock,https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture",Somerset
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,Spotlights,Home & Garden,New in box not needed Spotlights . Posted by s...,9.0,Newent,https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods,Gloucestershire

In [14]:
df = df.drop(df.columns[3], axis=1)
df
# df_trial = df[['category', 'location', 'subcategory', 'county']]

,id,product_name,category,price,location,url,page_id,create_time,subcategory,county
0,243809c0-9cfc-4486-ad12-3b7a16605ba9,Mirror wall art,Home & Garden,5.0,Wokingham,https://www.gumtree.com/p/mirrors-clocks-ornam...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture",Berkshire
1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,Stainless Steel Food Steamer,Home & Garden,20.0,Inverness,https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods,Highland
2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,Sun loungers,Home & Garden,20.0,Skegness,https://www.gumtree.com/p/outdoor-settings-fur...,1.426705e+09,2022-02-26,Garden & Patio,Lincolnshire
3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Home & Garden,115.0,Radstock,https://www.gumtree.com/p/other-dining-living-...,1.426705e+09,2022-02-26,"Dining, Living Room Furniture",Somerset
12,5707be4f-49d9-4feb-b2c8-aa0868405c65,Spotlights,Home & Garden,9.0,Newent,https://www.gumtree.com/p/other-household-good...,1.426705e+09,2022-02-26,Other Household Goods,Gloucestershire
...,...,...,...,...,...,...,...,...,...,...
11313,c4148656-78a9-4f3e-b393-134fdc5ef900,Sony PlayStation VR Move Bundle,Video Games & Consoles,260.0,Acocks Green,https://www.gumtree.com/p/ps4/sony-playstation...,1.422159e+09,2022-02-28,Consoles,West Midlands
11314,564e3411-768d-4250-a624-b119d696f103,Playstation VR V2 Bundle,Video Games & Consoles,235.0,Acocks Green,https://www.gumtree.com/p/ps4/playstation-vr-v...,1.422159e+09,2022-02-28,Consoles,West Midlands
11315,2b0a652b-46a2-4297-b619-5efeeb222787,Oculus quest 2 256gb,Video Games & Consoles,250.0,Montrose,https://www.gumtree.com/p/other-video-games/oc...,1.426669e+09,2022-02-28,Other Video Games & Consoles,Angus
11316,719fd40a-870e-4144-b324-55dff2e66fb4,Logitech driving force shifter,Video Games & Consoles,30.0,Carrickfergus,https://www.gumtree.com/p/other-video-game-acc...,1.426700e+09,2022-02-28,Video Game Accessories,County Antrim
11317,86d1806b-5575-4a7e-9160-f24f12be6c95,20 GAMES & NINTENDO SWITCH BUNDLE,Video Games & Consoles,450.0,Poole,https://www.gumtree.com/p/video-games/20-games...,1.426700e+09,2022-02-28,Games,Dorset

In [15]:
dummies = pd.get_dummies(df[['category']], prefix='category', drop_first=True)
dummies

,category_Baby & Kids Stuff,"category_Clothes, Footwear & Accessories",category_Computers & Software,category_DIY Tools & Materials,category_Health & Beauty,category_Home & Garden,"category_Music, Films, Books & Games",category_Office Furniture & Equipment,category_Other Goods,"category_Phones, Mobile Phones & Telecoms","category_Sports, Leisure & Travel",category_Video Games & Consoles
0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
11313,0,0,0,0,0,0,0,0,0,0,0,1
11314,0,0,0,0,0,0,0,0,0,0,0,1
11315,0,0,0,0,0,0,0,0,0,0,0,1
11316,0,0,0,0,0,0,0,0,0,0,0,1
11317,0,0,0,0,0,0,0,0,0,0,0,1

In [16]:
# features_columns = ['price']
# X = df.loc[:, features_columns]
# X.shape
dummies.columns




# X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3)
# X_validation, X_test, y_validation, y_test = model_selection.train_test_split(
#     X_test, y_test, test_size=0.5
# )

# print(X_train.shape, y_train.shape)

Index(['category_Baby & Kids Stuff ',
       'category_Clothes, Footwear & Accessories ',
       'category_Computers & Software ', 'category_DIY Tools & Materials ',
       'category_Health & Beauty ', 'category_Home & Garden ',
       'category_Music, Films, Books & Games ',
       'category_Office Furniture & Equipment ', 'category_Other Goods ',
       'category_Phones, Mobile Phones & Telecoms ',
       'category_Sports, Leisure & Travel ',
       'category_Video Games & Consoles '],
      dtype='object')

In [17]:
df_for_linear = pd.concat([df['price'], dummies], axis=1)
df_for_linear

,price,category_Baby & Kids Stuff,"category_Clothes, Footwear & Accessories",category_Computers & Software,category_DIY Tools & Materials,category_Health & Beauty,category_Home & Garden,"category_Music, Films, Books & Games",category_Office Furniture & Equipment,category_Other Goods,"category_Phones, Mobile Phones & Telecoms","category_Sports, Leisure & Travel",category_Video Games & Consoles
0,5.0,0,0,0,0,0,1,0,0,0,0,0,0
1,20.0,0,0,0,0,0,1,0,0,0,0,0,0
2,20.0,0,0,0,0,0,1,0,0,0,0,0,0
3,115.0,0,0,0,0,0,1,0,0,0,0,0,0
12,9.0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11313,260.0,0,0,0,0,0,0,0,0,0,0,0,1
11314,235.0,0,0,0,0,0,0,0,0,0,0,0,1
11315,250.0,0,0,0,0,0,0,0,0,0,0,0,1
11316,30.0,0,0,0,0,0,0,0,0,0,0,0,1
11317,450.0,0,0,0,0,0,0,0,0,0,0,0,1

In [18]:
X = df_for_linear.drop('price', axis=1)
y = df_for_linear['price']
X.shape

(6311, 12)

In [19]:
y.shape

(6311,)

In [20]:
reg = linear_model.LinearRegression()

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3)
X_validation, X_test, y_validation, y_test = model_selection.train_test_split(
    X_test, y_test, test_size=0.5
)
reg.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = reg.predict(X_test)
y_pred

array([  253.15787986,   145.44662379,   209.73842105,    83.14542466,
        4168.9367541 ,   209.73842105,   145.44662379,  1015.18829016,
         145.44662379,   247.09623239,    41.075     ,  1015.18829016,
         209.73842105,   530.06140704,   209.73842105, 37878.54307692,
         530.06140704,  1015.18829016,   530.06140704,  1015.18829016,
         209.73842105,   145.44662379,  1015.18829016,    41.075     ,
        4168.9367541 ,  1015.18829016,   530.06140704,  1406.76706349,
         145.44662379,  1015.18829016,  1406.76706349,   253.15787986,
         530.06140704,   145.44662379,   530.06140704,   281.0224024 ,
         281.0224024 ,   530.06140704,  4168.9367541 ,  4168.9367541 ,
        4168.9367541 ,    83.14542466,   209.73842105,   145.44662379,
        1406.76706349, 37878.54307692,   167.76964567,    41.075     ,
         281.0224024 ,    83.14542466,   530.06140704,  4168.9367541 ,
         530.06140704,  1406.76706349,  4168.9367541 ,   281.0224024 ,
        1406.76706349,   530.06140704, 37878.54307692,   247.09623239,
         167.76964567,  4168.9367541 ,   167.76964567,  1015.18829016,
        4168.9367541 ,   209.73842105,   530.06140704,    83.14542466,
        4168.9367541 ,  1015.18829016, 37878.54307692,   209.73842105,
         145.44662379,   530.06140704,   253.15787986,  1406.76706349,
          41.075     ,   209.73842105,   209.73842105,   167.76964567,
        4168.9367541 ,   530.06140704,  1015.18829016,   167.76964567,
         209.73842105,  4168.9367541 ,  1015.18829016,   253.15787986,
        1015.18829016,   281.0224024 ,  4168.9367541 ,   209.73842105,
          41.075     ,   145.44662379,  4168.9367541 ,   530.06140704,
          83.14542466,   253.15787986,   209.73842105,   167.76964567,
         167.76964567,   145.44662379,   281.0224024 ,   209.73842105,
          83.14542466,   530.06140704,  1015.18829016, 37878.54307692,
         247.09623239,   145.44662379,   530.06140704,   530.06140704,
         145.44662379,   253.15787986,  4168.9367541 ,    83.14542466,
        1406.76706349,   253.15787986,  4168.9367541 ,   281.0224024 ,
         253.15787986,   247.09623239,   145.44662379,    83.14542466,
        4168.9367541 ,    41.075     ,    41.075     ,   209.73842105,
          41.075     ,  1406.76706349,  1015.18829016,   209.73842105,
         145.44662379,   145.44662379,   209.73842105,   253.15787986,
          83.14542466,   167.76964567,   253.15787986,  1406.76706349,
       37878.54307692,    83.14542466,   167.76964567,   209.73842105,
         281.0224024 ,  1406.76706349,   253.15787986,   530.06140704,
         253.15787986,   167.76964567,   167.76964567,  4168.9367541 ,
         281.0224024 ,   167.76964567,   247.09623239,   530.06140704,
          41.075     ,  4168.9367541 ,    83.14542466,  1406.76706349,
         530.06140704, 37878.54307692, 37878.54307692,    41.075     ,
        4168.9367541 ,  1015.18829016,  4168.9367541 ,  1015.18829016,
         530.06140704,   281.0224024 ,    83.14542466,   281.0224024 ,
         145.44662379,   247.09623239,   209.73842105,    41.075     ,
          83.14542466,   209.73842105,   167.76964567, 37878.54307692,
         209.73842105,   209.73842105,  1406.76706349,   281.0224024 ,
       37878.54307692,   253.15787986,  4168.9367541 ,  1015.18829016,
         281.0224024 ,  4168.9367541 ,   281.0224024 ,   145.44662379,
         167.76964567,   145.44662379,   167.76964567,  4168.9367541 ,
          83.14542466,   247.09623239,  4168.9367541 ,   281.0224024 ,
        1015.18829016,   209.73842105,   247.09623239,    83.14542466,
         167.76964567,    83.14542466,    41.075     ,  4168.9367541 ,
          41.075     ,   281.0224024 ,    83.14542466,  4168.9367541 ,
         281.0224024 ,  1015.18829016,  4168.9367541 ,   281.0224024 ,
         530.06140704,   167.76964567,   530.06140704,  4168.9367541 ,
         209.73842105,    83.14542466, 37878.54307692,  4168.9367541 ,
         530.06140704,   247.09623239,   247.09623239, 37878.54307692,
         253.15787986,  1406.76706349,   167.76964567,   209.73842105,
        1406.76706349,   530.06140704,  4168.9367541 ,   145.44662379,
         247.09623239, 37878.54307692,  4168.9367541 , 37878.54307692,
         281.0224024 ,   253.15787986,   167.76964567,   530.06140704,
        4168.9367541 ,    83.14542466,  1015.18829016,    83.14542466,
        1406.76706349,   145.44662379,   167.76964567,   167.76964567,
         167.76964567,   247.09623239,   167.76964567,  4168.9367541 ,
         145.44662379,   281.0224024 ,   209.73842105,   530.06140704,
        1406.76706349, 37878.54307692,   247.09623239,  1406.76706349,
         530.06140704,  1406.76706349,  4168.9367541 ,    41.075     ,
        1015.18829016,   253.15787986,    83.14542466,   167.76964567,
        1406.76706349,   145.44662379,   281.0224024 ,  1406.76706349,
         247.09623239,    83.14542466,  4168.9367541 ,   167.76964567,
        1406.76706349,   209.73842105,   530.06140704,   145.44662379,
         253.15787986, 37878.54307692,   209.73842105,   145.44662379,
        1406.76706349,   281.0224024 ,   167.76964567,   167.76964567,
        1406.76706349,    41.075     ,   281.0224024 ,   167.76964567,
        4168.9367541 ,  4168.9367541 ,   167.76964567,    41.075     ,
        4168.9367541 ,  1406.76706349,    41.075     ,   281.0224024 ,
         253.15787986, 37878.54307692,  1406.76706349,  1406.76706349,
       37878.54307692,   145.44662379,  1406.76706349,   253.15787986,
         209.73842105,   167.76964567,   247.09623239,   530.06140704,
         281.0224024 ,   209.73842105,   145.44662379, 37878.54307692,
          83.14542466,  1015.18829016,   209.73842105,  1406.76706349,
         281.0224024 ,   281.0224024 ,  4168.9367541 ,   247.09623239,
          41.075     ,   247.09623239,   167.76964567, 37878.54307692,
         145.44662379,   145.44662379,  4168.9367541 ,   167.76964567,
        1015.18829016,   247.09623239,   167.76964567,    83.14542466,
         145.44662379,   145.44662379,   530.06140704,   247.09623239,
         247.09623239, 37878.54307692,   145.44662379,   281.0224024 ,
          83.14542466,   209.73842105,   145.44662379,   247.09623239,
         247.09623239,  4168.9367541 ,  1015.18829016, 37878.54307692,
        4168.9367541 ,   167.76964567,    83.14542466,   209.73842105,
        4168.9367541 ,    41.075     ,   209.73842105,  1406.76706349,
         253.15787986,   281.0224024 ,   145.44662379,   281.0224024 ,
         145.44662379,  1406.76706349,  4168.9367541 ,  1406.76706349,
         530.06140704,   167.76964567,   530.06140704,   209.73842105,
         209.73842105,   530.06140704,    83.14542466,   530.06140704,
         167.76964567,   209.73842105,  1015.18829016,    41.075     ,
         530.06140704,  1406.76706349,   530.06140704,  1406.76706349,
        1015.18829016,    41.075     ,   530.06140704,   253.15787986,
         209.73842105,   167.76964567,  4168.9367541 ,  1406.76706349,
         281.0224024 ,   145.44662379,  1015.18829016,   281.0224024 ,
         530.06140704,   167.76964567,  1406.76706349,    41.075     ,
         530.06140704,  4168.9367541 ,   167.76964567,   167.76964567,
         281.0224024 ,  1406.76706349,   167.76964567,   253.15787986,
         145.44662379,   145.44662379,    83.14542466,   167.76964567,
          41.075     ,   281.0224024 ,   167.76964567,  1406.76706349,
         530.06140704,  1015.18829016,   167.76964567,   209.73842105,
       37878.54307692,  1406.76706349, 37878.54307692,   281.0224024 ,
         167.76964567,    83.14542466, 37878.54307692,  1015.18829016,
         209.73842105,  1406.76706349,    41.075     ,  1015.18829016,
         530.06140704,  1406.76706349,   281.0224024 ,  1015.18829016,
          83.14542466,   145.44662379,   167.76964567,   145.44662379,
         247.09623239,   167.76964567,    83.14542466,   145.44662379,
          83.14542466,   530.06140704,    41.075     ,    83.14542466,
         167.76964567, 37878.54307692,  1406.76706349,   247.09623239,
          83.14542466,  4168.9367541 ,    83.14542466,   167.76964567,
         209.73842105,   209.73842105,   253.15787986,  1406.76706349,
          41.075     ,  4168.9367541 ,   530.06140704,   209.73842105,
         167.76964567,  1406.76706349,   145.44662379,   247.09623239,
         145.44662379,  1406.76706349,    83.14542466,   167.76964567,
         247.09623239,   281.0224024 ,   247.09623239,   281.0224024 ,
         167.76964567,   247.09623239,   145.44662379, 37878.54307692,
         247.09623239,   253.15787986,   167.76964567,   530.06140704,
       37878.54307692,   530.06140704,   530.06140704,   145.44662379,
       37878.54307692,   281.0224024 ,   530.06140704,  4168.9367541 ,
        1015.18829016,    83.14542466,  1406.76706349,   247.09623239,
         209.73842105,   247.09623239, 37878.54307692,   247.09623239,
        1015.18829016,  1406.76706349,  4168.9367541 ,   209.73842105,
        1406.76706349,    83.14542466,    83.14542466,  1015.18829016,
         209.73842105,   253.15787986,  4168.9367541 ,   209.73842105,
         281.0224024 ,   209.73842105, 37878.54307692,   209.73842105,
         530.06140704, 37878.54307692,   530.06140704,    83.14542466,
         167.76964567,    83.14542466,  1406.76706349,   209.73842105,
         281.0224024 ,  1406.76706349,    41.075     ,  4168.9367541 ,
        4168.9367541 ,    41.075     ,   145.44662379,   530.06140704,
         145.44662379,  1406.76706349,   530.06140704,   167.76964567,
         281.0224024 ,   209.73842105,   530.06140704,   281.0224024 ,
         253.15787986,   530.06140704,   167.76964567,    83.14542466,
         281.0224024 ,  4168.9367541 ,    41.075     ,    83.14542466,
       37878.54307692,    41.075     ,   530.06140704,   209.73842105,
         247.09623239,    83.14542466,   209.73842105,   247.09623239,
         167.76964567,   145.44662379,   530.06140704,  1015.18829016,
         530.06140704,   145.44662379,  1406.76706349,  1015.18829016,
        4168.9367541 ,   247.09623239,  1406.76706349,   247.09623239,
         167.76964567,  1406.76706349,   247.09623239,    83.14542466,
         530.06140704,   281.0224024 ,  1015.18829016,   253.15787986,
        1015.18829016,  4168.9367541 ,   253.15787986,   530.06140704,
        4168.9367541 ,   167.76964567,   145.44662379,   167.76964567,
         167.76964567,    83.14542466,   167.76964567,  1406.76706349,
         530.06140704,  4168.9367541 ,  4168.9367541 ,  1406.76706349,
         281.0224024 ,  1015.18829016,    83.14542466,  4168.9367541 ,
        4168.9367541 ,   530.06140704,   247.09623239,   167.76964567,
        1406.76706349,  4168.9367541 ,   209.73842105,  1406.76706349,
         530.06140704,   281.0224024 ,   167.76964567,   247.09623239,
          83.14542466,   281.0224024 ,   145.44662379,  4168.9367541 ,
         167.76964567,  1015.18829016,    83.14542466,  1015.18829016,
        1015.18829016,    83.14542466,   530.06140704,    41.075     ,
        1406.76706349,   281.0224024 ,    41.075     ,    83.14542466,
         530.06140704,   253.15787986,  4168.9367541 ,   167.76964567,
         253.15787986,   209.73842105,  4168.9367541 ,    41.075     ,
         530.06140704,   145.44662379,  1015.18829016,   145.44662379,
         281.0224024 ,  1015.18829016,   530.06140704,  1406.76706349,
         209.73842105,  4168.9367541 ,    41.075     ,   167.76964567,
         247.09623239,  1015.18829016, 37878.54307692,   167.76964567,
         247.09623239,    83.14542466,    41.075     ,   167.76964567,
        4168.9367541 ,  1406.76706349,    83.14542466,   209.73842105,
       37878.54307692,  4168.9367541 ,  1406.76706349,   247.09623239,
        4168.9367541 ,  1406.76706349,   167.76964567,   247.09623239,
         281.0224024 ,    83.14542466,   530.06140704,   145.44662379,
        4168.9367541 ,    83.14542466,  1406.76706349,   167.76964567,
        1015.18829016,   281.0224024 ,  4168.9367541 ,   145.44662379,
        1406.76706349,   145.44662379,   167.76964567,   209.73842105,
          41.075     ,   281.0224024 ,    41.075     ,   167.76964567,
         530.06140704, 37878.54307692,  1015.18829016,  1015.18829016,
        1406.76706349,   167.76964567,   281.0224024 , 37878.54307692,
          83.14542466,    83.14542466,   247.09623239,  1015.18829016,
         253.15787986,   167.76964567,   281.0224024 ,   530.06140704,
        1015.18829016,   281.0224024 ,   167.76964567,   167.76964567,
         167.76964567,   281.0224024 ,   167.76964567, 37878.54307692,
         281.0224024 ,   530.06140704,    83.14542466, 37878.54307692,
         167.76964567,   281.0224024 ,   145.44662379,   281.0224024 ,
         281.0224024 ,   530.06140704,  4168.9367541 ,   247.09623239,
        1015.18829016,   247.09623239,  1015.18829016,   167.76964567,
         145.44662379,   145.44662379,  1015.18829016,   145.44662379,
         253.15787986,    83.14542466,  4168.9367541 ,   209.73842105,
         209.73842105, 37878.54307692,   209.73842105,   167.76964567,
         253.15787986,  1406.76706349,   145.44662379,   209.73842105,
         145.44662379,  1015.18829016,   253.15787986,   253.15787986,
         281.0224024 ,   167.76964567,    83.14542466,   167.76964567,
         209.73842105,   253.15787986,   209.73842105,   530.06140704,
          83.14542466,    83.14542466,    41.075     ,   209.73842105,
         281.0224024 ,   145.44662379,   209.73842105,    83.14542466,
         253.15787986,  1015.18829016,    41.075     ,   209.73842105,
         253.15787986,   167.76964567, 37878.54307692,   167.76964567,
        4168.9367541 ,    83.14542466, 37878.54307692,   530.06140704,
         253.15787986,   253.15787986,   281.0224024 ,   145.44662379,
        1406.76706349,  1015.18829016,   253.15787986,   167.76964567,
       37878.54307692,   530.06140704,   167.76964567,   209.73842105,
         530.06140704, 37878.54307692,   209.73842105,   281.0224024 ,
        1406.76706349,   167.76964567,   281.0224024 ,   209.73842105,
          41.075     ,    83.14542466,   281.0224024 ,   530.06140704,
        4168.9367541 ,   247.09623239,   167.76964567,   530.06140704,
         145.44662379,    41.075     ,    83.14542466,   167.76964567,
         530.06140704,   281.0224024 ,   281.0224024 ,    83.14542466,
        1406.76706349,   247.09623239,    83.14542466,   167.76964567,
        1406.76706349,   530.06140704,    41.075     ,   145.44662379,
        1406.76706349,   209.73842105,   281.0224024 ,  1015.18829016,
         167.76964567,   209.73842105, 37878.54307692,   167.76964567,
        1406.76706349,  1015.18829016,  4168.9367541 ,   209.73842105,
          41.075     ,   281.0224024 ,   247.09623239,   247.09623239,
         145.44662379,  4168.9367541 ,   253.15787986,   281.0224024 ,
         167.76964567,   145.44662379,   145.44662379,    41.075     ,
          83.14542466,   167.76964567, 37878.54307692,   145.44662379,
          41.075     ,   253.15787986,    83.14542466,   209.73842105,
          41.075     ,   167.76964567,  1015.18829016,    83.14542466,
        1015.18829016,   530.06140704,   253.15787986, 37878.54307692,
        1406.76706349,    41.075     ,  1406.76706349,    41.075     ,
          83.14542466,   145.44662379,   281.0224024 ,    83.14542466,
         167.76964567,    83.14542466,  1015.18829016,    83.14542466,
        1406.76706349,    83.14542466,   530.06140704,  1015.18829016,
          83.14542466,   167.76964567,  1015.18829016,  1015.18829016,
         209.73842105,   145.44662379,   167.76964567,  1406.76706349,
          83.14542466,  1406.76706349,   145.44662379,  1015.18829016,
          41.075     ,   145.44662379,  1015.18829016,   167.76964567,
         167.76964567,  1015.18829016,  1406.76706349,    41.075     ,
         209.73842105,   167.76964567,    41.075     ,  4168.9367541 ,
         530.06140704,   281.0224024 ,  4168.9367541 , 37878.54307692,
        1406.76706349,   253.15787986,    41.075     ,    41.075     ,
          41.075     ,   145.44662379,   530.06140704,    41.075     ,
         247.09623239,   281.0224024 ,  4168.9367541 ,    41.075     ,
          41.075     ,   209.73842105,   209.73842105,   145.44662379,
         209.73842105,   167.76964567,   145.44662379,   530.06140704,
         145.44662379,   167.76964567,   530.06140704,   167.76964567,
         247.09623239,  1015.18829016,    41.075     ,   530.06140704,
          83.14542466,   247.09623239,   281.0224024 ,   530.06140704,
         530.06140704,   209.73842105, 37878.54307692,  1015.18829016,
        4168.9367541 ,   167.76964567,   281.0224024 ,   253.15787986,
       37878.54307692,   167.76964567, 37878.54307692])

In [26]:
df_image_uuid = pd.read_json('/Users/paddy/Desktop/AiCore/facebook_ml/images.json')
print(df_image_uuid.head())

                                     id                            product_id  \
0  912bb259-3ad9-457b-9db1-ce1da9016057  5f5f57d7-778f-4336-bb10-b43863418c8c
1  b166d305-b852-4bdd-83f4-465b20da94fa  5f5f57d7-778f-4336-bb10-b43863418c8c
2  68f5a29d-0075-4d60-81c1-ab684a82e50c  c2c8949f-3cde-4651-a234-4a4a1b2a9ad4
3  f6a309d7-d247-446a-9b5e-aceefdd4334d  c2c8949f-3cde-4651-a234-4a4a1b2a9ad4
4  2c2b3a6f-15b3-4289-937a-15482d9f5781  8292aa4e-7f1b-4655-bf0e-f1f2c9e3ffaf

                                         bucket_link         image_ref  \
0  https://aicore-product-images.s3.amazonaws.com...  koQAAOSwhZRiE5dD
1  https://aicore-product-images.s3.amazonaws.com...  9vgAAOSw8sRiE5dE
2  https://aicore-product-images.s3.amazonaws.com...  FlwAAOSwCkpiFNlV
3  https://aicore-product-images.s3.amazonaws.com...  4gIAAOSw4ORiFNlZ
4  https://aicore-product-images.s3.amazonaws.com...  sHoAAOSwQoRiD7vf

  create_time
0  2022-02-26
1  2022-02-26
2  2022-02-26
3  2022-02-26
4  2022-02-26

In [32]:
df_image_uuid.dtypes
df_image_uuid['id'] = df_image_uuid['id'].astype(str)

In [34]:
merged_df =  pd.merge(df, df_for_linear, how='inner', on=['id'])
merged_df

KeyError: 'id'